### ISSUE TITLE
Unable to build new model.

### ISSUE THREAD

**Issue by xenmind** [ngaiyin1760/LSTM-model-stock-price-movement-prediction-#1]
Hi Zedric,
 
First let me say that I think the concept of this loss function is fantastic and I look forward to experimenting with it. I tried running your code with TF 1.15 (CUDA 10.0, py 3.7.7, Win 10), and while the saved model loads and predicts, the fitting of new models fails. I'm not an expert on TF so I thought I'd ask you in case the problem was obvious.

The error is: 'FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value loss/dense_1_loss/Variable
 [[{{node loss/dense_1_loss/ScatterNdUpdate}}]]
 [[loss/mul/_103]]
  (1) Failed precondition: Attempting to use uninitialized value loss/dense_1_loss/Variable
 [[{{node loss/dense_1_loss/ScatterNdUpdate}}]]'
 
I tried to initialize the direction_loss variable (probably the wrong way to do this?):
'direction_loss = tf.scatter_nd_update(direction_loss.initialized_value(), indices, alpha*updates)'
 
But this led to: 'AttributeError: 'Tensor' object has no attribute '_lazy_read''
 
I wanted to confirm in the first instance that my TF version is compatible with your code. If so, do you 
have any idea how I might get the code running.
 
Thanks you for any help you might provide,
Gavin.

**Comment by xenmind** [comment]
Hi,

I solved the problem by adding the following line before the fit call:

'K.get_session().run(tf.initialize_all_variables())'

G

**Comment by ngaiyin1760** [comment]
Hi Gavin,

Sorry for late reply due to busy schedule recently. But it's nice to see that you have solved the problem.

Feel free to let me know if there are any issues. Actually, I think the idea still get much room to improve, but which may consume much time. Please let me know if you find some ways to improve the loss function. Thanks much.

Best regards,
Zedric Cheung

**Comment by xenmind** [comment]
Will do cheers.

G
